# Generated by Django 5.0.1 on 2025-11-18 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title', max_length=200)),
                ('location', models.CharField(help_text='e.g., Remote, Hybrid, On-site', max_length=100)),
                ('description', models.TextField(help_text='Full job description')),
                ('requirements', models.TextField(blank=True, help_text='Job requirements (optional)')),
                ('responsibilities', models.TextField(blank=True, help_text='Job responsibilities (optional)')),
                ('salary_range', models.CharField(blank=True, help_text='e.g., $50k-$70k (optional)', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Posting',
                'verbose_name_plural': 'Job Postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter')),
                ('resume', models.FileField(help_text='Upload resume (PDF, DOC, DOCX)', upload_to='resumes/%Y/%m/')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile (optional)')),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('interview', 'Interview Scheduled'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='new', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to candidate)')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications_reviewed', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
            },
        ),
    ]
