# Generated by Django 5.0.1 on 2025-11-18 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='approved_for_interview',
            field=models.BooleanField(default=False, help_text='Approved by hiring manager'),
        ),
        migrations.AddField(
            model_name='application',
            name='next_interviewer_email',
            field=models.EmailField(blank=True, help_text='Email of next person to interview (will integrate with Entra ID)', max_length=254),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_manager',
            field=models.ForeignKey(blank=True, help_text='Primary hiring manager for this position', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_managing', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='hiring_team',
            field=models.ManyToManyField(blank=True, help_text='Team members who can review applications', related_name='jobs_team_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes (visible to hiring team)'),
        ),
        migrations.CreateModel(
            name='InterviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(help_text='When the interview took place')),
                ('interview_type', models.CharField(blank=True, help_text='e.g., Phone Screen, Technical, Final', max_length=50)),
                ('notes', models.TextField(help_text='Interview notes and feedback')),
                ('recommendation', models.CharField(blank=True, choices=[('strong_yes', 'Strong Yes - Hire'), ('yes', 'Yes - Move Forward'), ('maybe', 'Maybe - Needs Discussion'), ('no', 'No - Do Not Advance'), ('strong_no', 'Strong No - Reject')], max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private (Only Me)'), ('team', 'Team (Hiring Team)'), ('all', 'All Reviewers')], default='team', help_text='Who can see this feedback', max_length=10)),
                ('shared_with_emails', models.TextField(blank=True, help_text='Additional team members to share with (comma-separated emails)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_notes', to='jobs.application')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Note',
                'verbose_name_plural': 'Interview Notes',
                'ordering': ['-interview_date'],
            },
        ),
    ]
