# Generated by Django 5.0.1 on 2025-11-18 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application_approved_for_interview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name (e.g., IT, HR, Finance)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this position belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='jobs.department'),
        ),
    ]
